defaults:
  - model: modular_leadmm_5_pre_post
  - metrics: default
  - datasets: digicam
  - dataloader: default
  - transforms: default
  - _self_

inferencer:
  device_tensors: ["lensless", "mask", "lensed"]
  device: auto
  save_path: "saved_reconstructions"
  seed: 42
  from_pretrained: null
  skip_model_load: false
